name: pubcrawl-dev

services:
  postgres:
    container_name: pubcrawl-dev-postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pubcrawl
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      timeout: 10s

  redis:
    container_name: pubcrawl-dev-redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres:
