mutation CreatePub(
	$capacity: Int!
	$isActive: Boolean!
	$occupancy: Int!
	$pubId: String!
	$pubKey: String!
	$queueStatus: Int!
	$displayName: String!
	$logo: String!
	$color: String!
) {
	insertIntoPubs(
		values: {
			capacity: $capacity
			isActive: $isActive
			occupancy: $occupancy
			pubId: $pubId
			pubKey: $pubKey
			queueStatus: $queueStatus
			displayName: $displayName
			logo: $logo
			color: $color
		}
	) {
		capacity
		id
		isActive
		occupancy
		pubId
		pubKey
		queueStatus
		displayName
		logo
		color
	}
}

mutation DecrementPubOccupancy($pubId: String!, $decrement: Int!) {
	decrementPubOccupancy(where: { pubId: $pubId }, values: { decrement: $decrement }) {
		id
		pubId
		occupancy
		capacity
		queueStatus
		isActive
		displayName
		logo
		color
	}
}

mutation IncrementPubOccupancy($pubId: String!, $increment: Int!) {
	incrementPubOccupancy(where: { pubId: $pubId }, values: { increment: $increment }) {
		id
		pubId
		occupancy
		capacity
		queueStatus
		isActive
		displayName
		logo
		color
	}
}

mutation RegeneratePubKeys($input: [RegeneratePubKeysInput!]!) {
	regeneratePubKeys(input: $input) {
		id
		pubId
		pubKey
	}
}

mutation RemovePub($pubId: String!) {
	deleteFromPubs(where: { pubId: { eq: $pubId } }) {
		id
		pubId
		pubKey
		occupancy
		capacity
		queueStatus
		isActive
		displayName
		logo
		color
	}
}

mutation UpdatePub($pub: PubsUpdateInput!, $oldPubId: String!) {
	updatePubs(set: $pub, where: { pubId: { eq: $oldPubId } }) {
		id
		pubId
		pubKey
		occupancy
		capacity
		queueStatus
		isActive
		displayName
		logo
		color
	}
}
