kind: Deployment
apiVersion: apps/v1
metadata:
  name: prostgres-test
  namespace: pubcrawl
  labels:
    app.kubernetes.io/component: prostgres-test
    app.kubernetes.io/instance: prostgres-test
    app.kubernetes.io/name: prostgres-test
    app.kubernetes.io/part-of: pubcrawl-test
    app.openshift.io/runtime: postgresql
    app.openshift.io/runtime-namespace: pubcrawl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prostgres-test
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prostgres-test
    spec:
      volumes:
        - name: prostgres-test
          persistentVolumeClaim:
            claimName: pubcrawl-test-postgres
      containers:
          name: prostgres-test
          image: 'image-registry.openshift-image-registry.svc:5000/pubcrawl/postgres-test'
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pubcrawl
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pubcrawl-test-postgres
              mountPath: /var/lib/postgresql/data
              subPath: pubcrawl
