#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(dirname -- "$0")/.." || exit

(
    cd web && pnpm run ci-check
) &
(
    cd db && pnpm run lint
) &

if ! wait; then
    echo "Pre-push checks failed"
    exit 1
fi
