name: Node DB CI (test) - Check and Build

on:
  pull_request:
    branches:
      - test
    paths:
      - db/**

jobs:
  ci-check:
    name: db-test-check-and-build # This name is used in github rules
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Use Node.js latest LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Lint
        working-directory: db
        run: pnpm lint

      - name: Check
        working-directory: db
        run: pnpm check

      - name: Formatting
        working-directory: db
        run: pnpm format:check

      - name: Build
        working-directory: db
        run: pnpm build
        env:
          DATABASE_URL: ""
          REDIS_URL: ""
