name: 'Node CI - Check and Build'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check and Build # This name is used in gihub rules
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Use Node.js latest LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Check code formatting
        run: pnpm run lint

      - name: SvelteKit check
        run: pnpm run check

      - name: Build
        run: pnpm run build
        env:
          ADMIN_KEY: tripp
          GRAPHQL_SUBSCRIPTIONS_URL: trapp
          PUBLIC_GRAPHQL_URL: trull
